spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/FREEPDB1
    username: DOCFLOW_EXP
    password: docflow_exp
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true    
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

logging:
  level:
    root: INFO
    com.docflow: DEBUG   # enables your aspect debug logs
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource.DataSourceUtils: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "loggers"]   # expose logger control
  endpoint:
    loggers:
      enabled: true

docflow:
  storage:
    type: filesystem
    filesystem:
      root: uploads
excel:
  target-table: loan_data
  primary-key: loan_no
  mappings:
    "LoanNo": "loan_no"
    "Amount": "amount"
    "Start Date": "start_date"
    "End Date": "end_date"
    "Monthly EMI": "monthly_emi"
    "Branch": "branch"
    "Total Installment": "total_installment"
    "User ID": "user_id"